server:
  port: 9904
eureka:
  instance:
    preferIpAddress: true
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:9900/eureka/

spring:
  freemarker:
    settings:
      classic_compatible: true
  application:
    name: web-service
  cloud:
    loadbalancer:
      retry:
        enabled: false